name: restlib_testing
description: A sample application
dependencies:
  restlib_common:
    git: https://code.google.com/p/dart-restlib.common/
  unittest: any

#dependencies:
#  js: any
#  unittest: any